# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\Scripts\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import ctypes
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QVBoxLayout, QLineEdit, QMessageBox, QApplication
from functools import partial
from total_function import Function_run

ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("myappid")

class Ui_stonemusic(object):
    def setupUi(self, stonemusic):
        stonemusic.setObjectName("stonemusic")
        stonemusic.resize(512, 768)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        stonemusic.setFont(font)
        self.centralwidget = QtWidgets.QWidget(stonemusic)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(32, 32, 160, 48))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(32, 96, 96, 48))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(32, 160, 160, 48))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(192, 36, 256, 36))
        self.lineEdit.setObjectName("lineEdit")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(384, 100, 64, 36))
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setMaximum(999)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(256, 96, 96, 48))
        self.label_4.setObjectName("label_4")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(160, 100, 64, 36))
        self.spinBox_2.setObjectName("spinBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(320, 168, 128, 36))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(192, 168, 128, 36))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(32, 224, 160, 48))
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(192, 228, 256, 36))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(32, 288, 160, 48))
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(192, 292, 256, 36))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(32, 352, 160, 48))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(192, 356, 256, 36))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(32, 416, 160, 48))
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(192, 420, 256, 36))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(32, 480, 160, 48))
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(192, 484, 256, 36))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(128, 560, 256, 48))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.start)
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(128, 632, 256, 48))
        self.pushButton_1.setObjectName("pushButton")
        self.pushButton_1.clicked.connect(self.closewindows)
        stonemusic.setCentralWidget(self.centralwidget)

        self.retranslateUi(stonemusic)
        QtCore.QMetaObject.connectSlotsByName(stonemusic)

    def retranslateUi(self, stonemusic):
        _translate = QtCore.QCoreApplication.translate
        stonemusic.setWindowTitle(_translate("stonemusic", "红石音乐辅助工具——by星羽漠"))
        current_dir = os.path.dirname(os.path.abspath(__file__))
        icon = QtGui.QPixmap(os.path.join(current_dir, "miku2.png"))
        stonemusic.setWindowIcon(QtGui.QIcon(icon))
        self.label.setText(_translate("stonemusic", "文件名："))
        self.label_2.setText(_translate("stonemusic", "音轨数："))
        self.label_3.setText(_translate("stonemusic", "midi_tick："))
        self.label_4.setText(_translate("stonemusic", "小节数："))
        self.radioButton.setText(_translate("stonemusic", "48"))
        self.radioButton_2.setText(_translate("stonemusic", "24"))
        self.label_5.setText(_translate("stonemusic", "notetrack："))
        self.label_6.setText(_translate("stonemusic", "notevolume："))
        self.label_7.setText(_translate("stonemusic", "com_track："))
        self.label_8.setText(_translate("stonemusic", "起始点："))
        self.label_9.setText(_translate("stonemusic", "RGB参数："))
        self.pushButton.setText(_translate("stonemusic", "运行"))
        self.pushButton_1.setText(_translate("stonemusic", "结束"))

    def start(self):
        try:
            midiname = self.lineEdit.text()
            soundtrack = eval(self.spinBox_2.text())
            num = eval(self.spinBox.text())
            if self.radioButton.isChecked():
                midi_tick = eval(self.radioButton.text())
            if self.radioButton_2.isChecked():
                midi_tick = eval(self.radioButton_2.text())
            noteblocktrack = eval(self.lineEdit_2.text())
            noteblockvolume = eval(self.lineEdit_3.text())
            commandtrack = eval(self.lineEdit_4.text())
            start_pos = eval(self.lineEdit_5.text())
            color_para = eval(self.lineEdit_6.text())
            Function_run().fun1(midiname, soundtrack, num, midi_tick, noteblocktrack, noteblockvolume, commandtrack, start_pos, color_para)
            result = True
        except Exception as e:
            result = False
            error_message = str(e)

        if result:
            successDialog = QMessageBox()
            successDialog.setWindowTitle('信息显示')
            successDialog.setText('正常运行')
            successDialog.exec_()
        else:
            errorDialog = QMessageBox()
            errorDialog.setWindowTitle('信息显示')
            errorDialog.setText('发生错误：' + error_message)
            errorDialog.exec_()

    def closewindows(self):
        QApplication.instance().quit()

